/*
 * MRSServer
 * Integration technology for deploying R analytics inside web, desktop, mobile, and dashboard applications as well as backend systems. Turn your R scripts into analytics web services, so code can be easily executed by applications running on a secure server.  The core APIs can be grouped into several categories, including: [Authentication](#authentication-apis), [Web Services](#services-management-apis), [Sessions](#session-apis), [Snapshots](#snapshot-apis), and [Status](#status-apis). 
 *
 * OpenAPI spec version: 9.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.SessionsidexecuteInputParameters;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse2003
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-20T15:38:57.574Z")
public class InlineResponse2003 {
  @SerializedName("success")
  private Boolean success = null;

  @SerializedName("errorMessage")
  private String errorMessage = null;

  @SerializedName("outputParameters")
  private List<SessionsidexecuteInputParameters> outputParameters = new ArrayList<SessionsidexecuteInputParameters>();

  @SerializedName("consoleOutput")
  private String consoleOutput = null;

  @SerializedName("changedFiles")
  private List<String> changedFiles = new ArrayList<String>();

  public InlineResponse2003 success(Boolean success) {
    this.success = success;
    return this;
  }

   /**
   * The operation was successful.
   * @return success
  **/
  @ApiModelProperty(example = "null", value = "The operation was successful.")
  public Boolean getSuccess() {
    return success;
  }

  public void setSuccess(Boolean success) {
    this.success = success;
  }

  public InlineResponse2003 errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * Errors returned by the execution.
   * @return errorMessage
  **/
  @ApiModelProperty(example = "null", value = "Errors returned by the execution.")
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }

  public InlineResponse2003 outputParameters(List<SessionsidexecuteInputParameters> outputParameters) {
    this.outputParameters = outputParameters;
    return this;
  }

  public InlineResponse2003 addOutputParametersItem(SessionsidexecuteInputParameters outputParametersItem) {
    this.outputParameters.add(outputParametersItem);
    return this;
  }

   /**
   * Output parameters for the execution.
   * @return outputParameters
  **/
  @ApiModelProperty(example = "null", value = "Output parameters for the execution.")
  public List<SessionsidexecuteInputParameters> getOutputParameters() {
    return outputParameters;
  }

  public void setOutputParameters(List<SessionsidexecuteInputParameters> outputParameters) {
    this.outputParameters = outputParameters;
  }

  public InlineResponse2003 consoleOutput(String consoleOutput) {
    this.consoleOutput = consoleOutput;
    return this;
  }

   /**
   * The console output of the execution.
   * @return consoleOutput
  **/
  @ApiModelProperty(example = "null", value = "The console output of the execution.")
  public String getConsoleOutput() {
    return consoleOutput;
  }

  public void setConsoleOutput(String consoleOutput) {
    this.consoleOutput = consoleOutput;
  }

  public InlineResponse2003 changedFiles(List<String> changedFiles) {
    this.changedFiles = changedFiles;
    return this;
  }

  public InlineResponse2003 addChangedFilesItem(String changedFilesItem) {
    this.changedFiles.add(changedFilesItem);
    return this;
  }

   /**
   * The filenames of the files modified during execution.
   * @return changedFiles
  **/
  @ApiModelProperty(example = "null", value = "The filenames of the files modified during execution.")
  public List<String> getChangedFiles() {
    return changedFiles;
  }

  public void setChangedFiles(List<String> changedFiles) {
    this.changedFiles = changedFiles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003 inlineResponse2003 = (InlineResponse2003) o;
    return Objects.equals(this.success, inlineResponse2003.success) &&
        Objects.equals(this.errorMessage, inlineResponse2003.errorMessage) &&
        Objects.equals(this.outputParameters, inlineResponse2003.outputParameters) &&
        Objects.equals(this.consoleOutput, inlineResponse2003.consoleOutput) &&
        Objects.equals(this.changedFiles, inlineResponse2003.changedFiles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(success, errorMessage, outputParameters, consoleOutput, changedFiles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003 {\n");
    
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    outputParameters: ").append(toIndentedString(outputParameters)).append("\n");
    sb.append("    consoleOutput: ").append(toIndentedString(consoleOutput)).append("\n");
    sb.append("    changedFiles: ").append(toIndentedString(changedFiles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

