/*
 * MRSServer
 * Integration technology for deploying R analytics inside web, desktop, mobile, and dashboard applications as well as backend systems. Turn your R scripts into analytics web services, so code can be easily executed by applications running on a secure server.  The core APIs can be grouped into several categories, including: [Authentication](#authentication-apis), [Web Services](#services-management-apis), [Sessions](#session-apis), [Snapshots](#snapshot-apis), and [Status](#status-apis). 
 *
 * OpenAPI spec version: 9.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * SessionsidexecuteInputParameters
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-20T15:38:57.574Z")
public class SessionsidexecuteInputParameters {
  @SerializedName("name")
  private String name = null;

  @SerializedName("value")
  private Object value = null;

  public SessionsidexecuteInputParameters name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the workspace object.
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "The name of the workspace object.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SessionsidexecuteInputParameters value(Object value) {
    this.value = value;
    return this;
  }

   /**
   * Value of the object as JSON.
   * @return value
  **/
  @ApiModelProperty(example = "null", value = "Value of the object as JSON.")
  public Object getValue() {
    return value;
  }

  public void setValue(Object value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionsidexecuteInputParameters sessionsidexecuteInputParameters = (SessionsidexecuteInputParameters) o;
    return Objects.equals(this.name, sessionsidexecuteInputParameters.name) &&
        Objects.equals(this.value, sessionsidexecuteInputParameters.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionsidexecuteInputParameters {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

